spring:
  application:
    name: Login
  output:
    ansi:
      enabled: always

### Database
 #datasource:
 #  url: url
 #  username: username
 #  password: pass

 #jpa:
 #  show-sql: true
 #  hibernate:
 #    ddl-auto: none
 #  properties:
 #    hibernate:
 #      dialect: dialect
